site_name:           SauterSchwabQuadrature
repo_url:            https://github.com/ga96tik/SauterSchwabQuadrature.jl
site_description:    Description for SauterSchwabQuadrature
site_author:         ga96tik


markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/config/Accessible-full.js
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Tutorials: test.md
